version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: openid-federation-user
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: openid-federation-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openid_network

networks:
  openid_network:
    driver: bridge

volumes:
  postgres_data: