name: Run CI
on:
  push:
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt-hotspot
          java-version: 17

      - name: Build the stack
        run: docker-compose -f docker/docker-compose.yaml up -d

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for Gradlew (Linux/Mac)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build
        env:
          DATASOURCE_USER: ${{ secrets.DATASOURCE_USER }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
